"""Tests for the runtime Bitwise-Cyclic-Tag interpreter written in S5 (bct/).

Every test runs the *actual* S5 executor (in-process, like the ctag/ suite)
with the machine generated by bct._gen_bct.build_interpreter, feeding the
BCT instance (plen, program bits, dlen, data bits) through stdin, and checks
the resulting tick counter against the definitional reference in
bct.reference.

The interpreter is *constant size*: the same fixed bct/s/bct.s5 executes any
BCT machine, growing the universe at runtime as the data buffer expands.
"""
import io
import os
import random
import subprocess
import sys
import contextlib
from pathlib import Path

HERE = Path(__file__).parent
ROOT = HERE.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from s5 import (
    Parser,
    Executor,
    S5Set,
    SubroutineSet,
    tokenize_files,
    set_value,
    Opcode,
    Instruction,
)

from bct.reference import (
    simulate,
    steps as ref_steps,
    peak_word_length as ref_peak,
)
from _gen_bct import (
    build_interpreter,
    ZERO,
    ONE,
    SUCC,
    PP,
    PLEN,
    I,
    W,
    DH,
    DT,
    BIT,
    SC,
    CONT,
    EQN,
    TMP,
    PBOUND,
    STR,
    PBC,
    P_BASE,
)

PRELUDE = [
    str(ROOT / "arithmetic" / "init.s5"),
    str(ROOT / "arithmetic" / "succ.s5"),
]


def _payload(program, data):
    lines = [str(len(program))]
    lines += list(program)
    lines.append(str(len(data)))
    lines += list(data)
    return "\n".join(lines) + "\n"


def _mounted(program, data, **kw):
    """Run init.s5 + succ.s5 + the interpreter on (program, data); return executor."""
    files = PRELUDE + [str(HERE / "bct.s5")]
    tokens = list(tokenize_files(files))
    instructions = Parser(tokens).parse_program()
    old_stdin = sys.stdin
    sys.stdin = io.StringIO(_payload(program, data))
    try:
        executor = Executor(buf_sizes={0: 256, 1: 256, 2: 256})
        status = executor.run(instructions)
    finally:
        sys.stdin = old_stdin
    assert status == "finished", f"program did not finish: {status}"
    return exec.utor


def _read(ex, slot):
    return set_value(ex.U[slot])


class TestRuns:
    """End-to-end: the S5 interpreter reproduces the definitional trace."""

    CASES = [
        ("0", "101"),
        ("0", "1"),
        ("1", "0"),
        ("10", "11"),
        ("01", "100"),
        ("110", "101"),
        ("101001", "1110"),
        ("1110", "1011"),
        ("00", "11"),
        ("1101", "11111"),
        ("1001", "101101"),
    ]

    def test_step_count_matches_reference(self):
        for program, data in self.CASES:
            ex = _mounted(program, data)
            expected = ref_steps(program, data)
            got = _read(ex, SC)
            assert got == expected, (
                f"P={program!r} d={data!r}: ticks={got}, expected {expected}"
            )

    def test_word_empty_after_halt(self):
        for program, data in self.CASES:
            ex = _mounted(program, data)
            assert ex.U[DH] == ex.U[DT], (
                f"P={program!r} d={data!r}: DH != DT after halt"
            )

    def test_pp_stays_within_program_region(self):
        for program, data in self.CASES:
            ex = _mounted(program, data)
            lo, hi = _read(ex, PBC), _read(ex, PBOUND)
            pp = _read(ex, PP)
            assert lo <= pp <= hi, (
                f"P={program!r} d={data!r}: PP={pp} outside [{lo}, {hi}]"
            )

    def test_data_buffer_grew_to_reference_peak(self):
        # the runtime-grown universe must contain every data bit ever produced
        for program, data in self.CASES:
            ex = _mounted(program, data)
            peak = ref_peak(program, data)
            assert len(ex.U) >= _read(ex, PBC) + peak, (
                f"P={program!r} d={data!r}: universe too small "
                f"({len(ex.U)} slots) for peak {peak}"
            )


class TestEdgeCases:
    def test_empty_data_had_zero_ticks(self):
        ex = _mounted("100", "")
        assert _read(ex, SC) == 0
        assert ex.U[DH] == ex.U[DT]

    def test_all_zero_program(self):
        # never appends useful bits; 8 ones each append one '0', so the
        # word needs 16 + 8 = 24 pops to drain
        ex = _mounted("0", "1")
        assert _read(ex, SC) == 2
        ex = _mounted("0000000000", "1" * 8 + "0" * 8)
        assert _read(ex, SC) == 24

    def test_all_zero_data(self):
        # head bits are always 0 -> 6 deletes, then halt
        ex = _mounted("11", "0" * 6)
        assert _read(ex, SC) == 6

    def test_single_bit_both_values(self):
        assert _read(_mounted("0", "0"), SC) == 1
        assert _read(_mounted("1", "0"), SC) == 1


class TestRandomizedEquivalence:
    """Random small machines that halt: interpreter == reference, tick for tick."""

    def test_random_halting_machines(self):
        rng = random.Random(20260817)
        checked = 0
        for _ in range(120):
            program = "".join(rng.choice("01") for _ in range(rng.randint(1, 6)))
            data = "".join(rng.choice("01") for _ in range(rng.randint(0, 10)))
            try:
                expected = ref_steps(program, data, max_ticks=4000)
            except ValueError:
                continue  # non-halting machines are out of scope for the battery
            ex = _mounted(program, data)
            assert _read(ex, SC) == expected, (
                f"P={program!r} d={data!r}: ticks={_read(ex, SC)}, "
                f"expected {expected}"
            )
            checked += 1
        assert checked >= 40, f"only {checked} halting machines found (bad seed)"


class TestStructures:
    """The interpreter is a fixed structure with the right shape."""

    def test_str_is_four_subroutines(self):
        ex = _mounted("0", "1")
        assert len(ex.U[STR]) == 4
        for i in range(4):
            assert isinstance(ex.U[STR][i], SubroutineSet), (
                f"STR[{i}] is {type(ex.U[STR][i]).__name__}, not a subroutine"
            )

    def test_body_sizes(self):
        bodies = {0: 17, 1: 8, 2: 28, 3: 1}
        ex = _mounted("101", "11")
        for i, size in bodies.items():
            assert len(ex.U[STR][i]._body) == size, (
                f"STR[{i}] body has {len(ex.U[STR][i]._body)} instrs, "
                f"expected {size}"
            )

    def test_pbc_is_canonical_p_base(self):
        ex = _mounted("0", "1")
        assert _read(ex, PBC) == P_BASE
        assert _read(ex, PBOUND) == P_BASE + 1  # program "0" has length 1


class TestPrintedResult:
    """The interpreter prints the tick count on stdout."""

    def test_prints_tick_count(self):
        buf = io.StringIO()
        old_stdin, old_stdout = sys.stdin, sys.stdout
        sys.stdin = io.StringIO(_payload("101001", "1110"))
        files = PRELUDE + [str(HERE / "bct.s5")]
        instructions = Parser(list(tokenize_files(files))).parse_program()
        try:
            with contextlib.redirect_stdout(buf):
                executor = Executor(buf_sizes={0: 256, 1: 256, 2: 256})
                status = executor.run(instructions)
        finally:
            sys.stdin, sys.stdout = old_stdin, old_stdout
        assert status == "finished"
        assert buf.getvalue().strip() == "11"  # ref_steps("101001", "1110")


class TestCLI:
    """The committed bct.s5 runs under the real command-line interpreter."""

    def test_cli_subprocess(self):
        env = dict(os.environ)
        env["PYTHONPATH"] = str(ROOT) + os.pathsep + env.get("PYTHONPATH", "")
        proc = subprocess.run(
            [
                sys.executable,
                "-m",
                "s5",
                "--bufsize",
                "256",
                str(ROOT / "arithmetic" / "init.s5"),
                str(ROOT / "arithmetic" / "succ.s5"),
                str(HERE / "bct.s5"),
            ],
            input=_payload("1101", "11111"),
            capture_output=True,
            text=True,
            env=env,
            timeout=60,
        )
        assert proc.returncode == 0, f"exit {proc.returncode}: {proc.stderr}"
        assert proc.stdout.strip() == "24", (
            f"expected 24 ticks, got {proc.stdout.strip()!r}"
        )


class TestUnboundedBuffer:
    """The data buffer is not capped (unlike the fixed ctag showcase)."""

    def test_grows_past_any_fixed_capacity(self):
        # peak word length 72 > any fixed buffer layout: the interpreter must
        # grow U at runtime and still agree with the reference tick count
        program, data = "10", "1" * 12 + "0" * 60
        assert ref_peak(program, data) == 72
        ex = _mounted(program, data)
        assert _read(ex, SC) == ref_steps(program, data) == 104
        # the whole run (program + data + registers) lives in the grown universe
        assert len(ex.U) == _read(ex, DT)
        assert _read(ex, PBC) + 72 <= len(ex.U)


class TestReference:
    """The definitional reference's own contract."""

    def test_empty_program_rejected(self):
        try:
            simulate("", "101")
        except ValueError as e:
            assert "non-empty" in str(e)
        else:
            raise AssertionError("expected ValueError for empty program")

    def test_termination_cap(self):
        try:
            ref_steps("1", "1", max_ticks=10)  # never halts
        except ValueError as e:
            assert "halt" in str(e)
        else:
            raise AssertionError("expected ValueError for non-halting machine")


if __name__ == "__main__":
    import pytest

    sys.exit(pytest.main([__file__, "-v"]))