"""Tests for the Cyclic Tag interpreter written in S5 (ctag/).

Every test runs the *actual* S5 executor (in-process, like the arithmetic
suite) with the machine generated by ctag._gen_ctag.build_ctag, and checks
the resulting universe state against the definitional reference in
ctag.reference.

Prerequisite universe setup mirrors arithmetic: init.s5 grows U to 32 and
installs ZERO/ONE, succ.s5 installs NORM_SUCC at U[6][0].  The generated
program grows U from 32 to 128 and runs the machine to completion.
"""
import sys
from pathlib import Path

HERE = Path(__file__).parent
ROOT = HERE.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from s5 import (
    Parser,
    Executor,
    S5Set,
    SubroutineSet,
    tokenize_files,
    set_value,
    Opcode,
    Instruction,
)

from reference import simulate, steps as ref_steps
from _gen_ctag import build_ctag, CTAG, PROD, BIT, CONT, EQN, TMP, PH, PT, PM
from _gen_ctag import SC, ZERO, ONE, SUCC  # noqa: F401


def _mounted(productions, initial_data, **kw):
    """Run init.s5 + succ.s5 + the generated machine, return (executor, steps)."""
    files = [
        str(ROOT / "arithmetic" / "init.s5"),
        str(ROOT / "arithmetic" / "succ.s5"),
    ]
    tokens = list(tokenize_files(files))
    instructions = Parser(tokens).parse_program()
    instructions += build_ctag(productions, initial_data, **kw)
    executor = Executor(buf_sizes={0: 256, 1: 256, 2: 256})
    status = executor.run(instructions)
    assert status == "finished", f"program did not finish: {status}"
    return executor


def _read(ex, slot):
    return set_value(ex.U[slot])


def _set(ex, slot, value):
    items = list(ex.U._items)
    items[slot] = _ints(value) if isinstance(value, int) else value
    ex.U = S5Set._from_items(items)


from s5 import int_to_s5set as _ints  # noqa: E402


def _select_and_call(ex, structure_slot, index):
    ex.C = ex.U[structure_slot]
    ex.exec_instruction(Instruction(Opcode.SUBSET_SELECT, n=index))
    ex.exec_instruction(Instruction(Opcode.SUBR))


class TestRuns:
    """End-to-end: the S5 machine executes exactly the definitional trace."""

    CASES = [
        (["0", ""], "101"),
        (["0", ""], "1"),
        (["1"], "0"),
        (["", ""], "110"),
        (["00", "1"], "1"),
        (["00", "1"], "10"),
        (["", "", ""], "11010"),
        (["0", ""], ""),
    ]

    def test_step_count_matches_reference(self):
        for productions, data in self.CASES:
            ex = _mounted(productions, data)
            expected = ref_steps(productions, data)
            got = _read(ex, SC)
            assert got == expected, (
                f"P={productions} d={data!r}: STEPCOUNT={got}, "
                f"expected {expected}"
            )

    def test_word_empty_after_halt(self):
        for productions, data in self.CASES:
            ex = _mounted(productions, data)
            assert ex.U[PH] == ex.U[PT], (
                f"P={productions} d={data!r}: PH != PT after halt "
                f"({_read(ex, PH)} vs {_read(ex, PT)})"
            )

    def test_production_index_stays_in_range(self):
        for productions, data in self.CASES:
            ex = _mounted(productions, data)
            assert _read(ex, PM) < len(productions) and _read(ex, PM) >= 0, (
                f"P={productions} d={data!r}: PM={_read(ex, PM)} out of range"
            )


class TestBuiltinProgram:
    """The committed ctag/ctag.s5 realises P=["0",""], data="101"."""

    def test_committed_file_runs(self):
        files = [
            str(ROOT / "arithmetic" / "init.s5"),
            str(ROOT / "arithmetic" / "succ.s5"),
            str(HERE / "ctag.s5"),
        ]
        tokens = list(tokenize_files(files))
        instructions = Parser(tokens).parse_program()
        executor = Executor(buf_sizes={0: 256, 1: 256, 2: 256})
        import contextlib
        import io
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            status = executor.run(instructions)
        assert status == "finished"
        assert _read(executor, SC) == 5
        assert executor.U[PH] == executor.U[PT]
        assert buf.getvalue().strip() == "5"


class TestDispatchAppend:
    """The production-dispatch routine directly (one append, no loop)."""

    def test_appends_bit_to_head_free_slot(self):
        ex = _mounted(["1"], "", n=8)
        # Seed: PM=0, PT=first free slot, PH anyway.
        _set(ex, PM, 0)
        items = list(ex.U._items)
        items[PT] = _ints(64 + 3)
        ex.U = S5Set._from_items(items)
        _select_and_call(ex, CTAG, 1)          # DISPATCH_APPEND
        assert ex.U[67] == _ints(1), "production '1' should set U[67]=1"
        assert _read(ex, PT) == 68, "tail pointer should advance by 1"

    def test_appends_two_bits(self):
        ex = _mounted(["10"], "", n=8)
        _set(ex, PM, 0)
        items = list(ex.U._items)
        items[PT] = _ints(64 + 2)
        ex.U = S5Set._from_items(items)
        _select_and_call(ex, CTAG, 1)
        assert ex.U[66] == _ints(1)
        assert ex.U[67] == _ints(0)
        assert _read(ex, PT) == 68


class TestResetPM:
    """Production-index wrap: RESET_PM zeroes PM."""

    def test_reset(self):
        ex = _mounted(["1"], "", n=4)
        _set(ex, PM, 1)
        _select_and_call(ex, CTAG, 2)
        assert _read(ex, PM) == 0

    def test_wrap_path_inside_step(self):
        # n=1: succ(0)=1 == n, so after any tick PM must be back to 0.
        ex = _mounted(["1"], "0")
        assert _read(ex, PM) == 0
        assert _read(ex, SC) == 1


class TestStructures:
    """The generated structures are the right shapes."""

    def test_ctag_structure(self):
        ex = _mounted(["0", ""], "")
        assert len(ex.U[CTAG]) == 3
        for i in range(3):
            assert isinstance(ex.U[CTAG][i], SubroutineSet)

    def test_prod_structure(self):
        ex = _mounted(["0", "10"], "")
        assert len(ex.U[PROD]) == 2
        for i in range(2):
            assert isinstance(ex.U[PROD][i], SubroutineSet)

    def test_bodies_len(self):
        ex = _mounted(["0", "101"], "")
        assert len(ex.U[CTAG][0]._body) == 28      # STEP
        assert len(ex.U[CTAG][1]._body) == 3        # DISPATCH_APPEND
        assert len(ex.U[CTAG][2]._body) == 1        # RESET_PM
        assert len(ex.U[PROD][0]._body) == 6        # P[0]="0": 1 bit x (write + incr)
        assert len(ex.U[PROD][1]._body) == 18       # P[1]="101": 3 bits


class TestOverflowGuard:
    def test_generator_refuses_overflow(self):
        try:
            # halting machine, but peak buffer use 72 > capacity 48
            build_ctag(["1", ""], "1" * 12 + "0" * 60)
        except ValueError as e:
            assert "buffer" in str(e)
        else:
            raise AssertionError("expected ValueError on overflow")


class TestBufferGrowth:
    """Generated code grows U to 128 before using high slots."""

    def test_universe_128(self):
        ex = _mounted(["0", ""], "1")
        assert len(ex.U) == 128

    def test_slots_have_data(self):
        ex = _mounted(["00", "1"], "1")
        # initial word '1' occupies U[64]; after tick 0 it appends '00' at U[65],U[66]
        assert ex.U[64] == _ints(1) or _read(ex, PH) != 64  # head may have moved
        assert set_value(ex.U[66]) in (0, 1)